version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    networks:
      - app-network

  customer-service:
    build: ./customer-service
    ports:
      - "8081:8081"
    networks:
      - app-network

  payment-service:
    build: ./payment-service
    ports:
      - "8082:8082"
    networks:
      - app-network

  audit-service:
    build: ./audit-service
    ports:
      - "8083:8083"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge